checks:
  argument-count:
    config:
      threshold: 8
  similar-code:
    config:
      threshold: 150
  method-count:
    config:
      threshold: 30
  method-lines:
    config:
      threshold: 35

exclude_patterns:
- "**/test/"
- "**/androidTest/"
- "**test"
