checks:
  argument-count:
    config:
      threshold: 8
  similar-code:
    config:
      threshold: 600
  method-count:
    config:
      threshold: 50
  method-lines:
    config:
      threshold: 40
  method-complexity:
    config:
      threshold: 25
  file-lines:
    config:
      threshold: 300
exclude_patterns:
- "**/test/"
- "**/androidTest/"
- "**test"
